---
- name: Install docker
  gather_facts: No
  hosts: 52.214.23.130
  user: centos
  become: yes
  
  tasks:
    - name: Install yum utils
      yum:
        name: "{{ item }}"
        state: latest
        with_items:
                - yum-utils
                - device-mapper-persistent-data
                - lvm2
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
        mode: 0644
    - name: Install Docker
      yum:
        name: docker-ce
        state: latest
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
